# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Take photo of github.com
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
        with:
          url: https://github.com
          screenshotName: main
      - name: push to branch
        run: |
          set -x
          git status
          git add screenshots
          git checkout -b screenshots
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -m 'update screenshot'
          git push origin screenshots -f
